### ISSUE TITLE
db.query('* b c') when false

### ISSUE THREAD

**Issue by NHQ** [incrediblesound/nebulaDB#1]
``` js
db.save('johnny hugs bear')

db.query('* hugs johnny', cb)

```

```
/nebulaDB/src/record.js:24
    entry = file[(index % ((page > 0 ? page : 1)*1000) )+1].split('<>'); //[ '\n<
                                                            ^
TypeError: Cannot call method 'split' of undefined
```

**Comment by incrediblesound** [comment]
Howdy Johnny!

Fixed that bug there, now a query with no results should return null. Also added error first format for the callbacks. FYI I am no pro database dev so this DB probably should not be used in anything mission critical! Maybe I should add a disclaimer to the readme...?

That being said, I enjoy this project a lot and only stopped working on it because nobody was using it or contributing to it. If you play around with it and find bugs or quirks I'll try my best to fix them and continue to improve the codebase.
